using NUnit.Framework;
using UnityEngine;
using UnityEngine.InputSystem;

public class PauseMenu : MonoBehaviour {

    public GameObject pauseMenu;

    public static bool isPaused = false;  

    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start() {
        pauseMenu.SetActive(false);
    }
/*
    // Update is called once per frame
    void FixedUpdate() {
        if (Input.GetKeyDown(KeyCode.P)) {
            if (isPaused) {
                ResumeGame();
            }
            else {
                PauseGame();
            }
        }
    }

    public void PauseGame() {
        pauseMenu.SetActive(true);
        Time.timeScale = 0f;
        isPaused = true;
    }

    public void ResumeGame() {
        pauseMenu.SetActive(false);
        Time.timeScale = 1f;
        isPaused = false;
    }
*/

}
